name: ğŸš€ FTP Deploy
on: [push, workflow_dispatch]
jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›’ Checkout
        uses: actions/checkout@v2
      - name: ğŸ”‘ Load Certificate
        run: echo "${{ secrets.FTP_CERTIFICATE }}" > ~/ftp.crt
      - name: ğŸ“¦ Get lftp
        run: sudo apt install lftp
      - name: ğŸ“„ Upload File
        run: lftp -e "set ssl:ca-file ~/ftp.crt; put -O /destination/ ./README.md" -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_HOSTNAME }}
      - name: ğŸ“ Upload Folder
        run: lftp -e "set ssl:ca-file ~/ftp.crt; mirror --parallel=100 -R ./ffmpeg/ /ffmpeg/" -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_HOSTNAME }}