name: ğŸš€ FTP Deploy
on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/*"
    branches:
      - main
jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    name: Upload
    steps:
      - name: ğŸ›’ Checkout
        uses: actions/checkout@v2
      - name: ğŸ“¦ Get lftp
        run: sudo apt install lftp
      - name: ğŸ“„ Upload File
        run: lftp -e "set ftp:ssl-allow no; put -O /destination/ ./README.md" -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_HOSTNAME }}
      - name: ğŸ“ Upload Folder
        run: lftp -e "set ftp:ssl-allow no; mirror --parallel=100 -R ./ffmpeg/ /ffmpeg/" -u ${{ secrets.`FTP_USERNAME` }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_HOSTNAME }}
