name: ğŸš€ FTP Deploy
on: push
jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    name: Upload
    steps:
      - name: ğŸ›’ Checkout
        uses: actions/checkout@v2
      - name: ğŸ“¦ Get lftp
        run: sudo apt install lftp
      - name: ğŸ”‘ Load Secrets
        run: echo "machine ${{ secrets.FTP_HOSTNAME }} login ${{ secrets.FTP_USERNAME }} password ${{ secrets.FTP_PASSWORD }}" > $HOME/.netrc
      - name: ğŸ“„ Upload File
        run: lftp -e "set ftp:ssl-allow no; put -O /destination/ ./README.md" ${{ secrets.FTP_HOSTNAME }}
      - name: ğŸ“ Upload Folder
        run: lftp -e "set ftp:ssl-allow no; mirror --parallel=100 -R ./ffmpeg/ /ffmpeg/" ${{ secrets.FTP_HOSTNAME }}
